// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Badge': string;
  'Content': string;
  'Wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
