// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Typography': string;
  'Typography_size--h1': string;
  'Typography_size--h2': string;
  'Typography_size--h3': string;
  'Typography_size--h4': string;
  'Typography_size--h5': string;
  'Typography_size--p': string;
  'Typography_size--span': string;
  'Typography_weight--400': string;
  'Typography_weight--500': string;
  'Typography_weight--600': string;
}
export const cssExports: CssExports;
export default cssExports;
