// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Arrow': string;
  'Input': string;
  'Option': string;
  'Options': string;
  'Search': string;
  'Select': string;
}
export const cssExports: CssExports;
export default cssExports;
