// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Container': string;
  'Container__enter': string;
  'Container__enterActive': string;
  'Container__exit': string;
  'Container__exitActive': string;
  'Content': string;
  'Footer': string;
  'Header': string;
  'Overlay': string;
  'Overlay__enter': string;
  'Overlay__enterActive': string;
  'Overlay__exit': string;
  'Overlay__exitActive': string;
  'Wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
